### ISSUE TITLE
Notification component

### ISSUE THREAD

**Issue by hschhhwwwo0o** [StellRay666s/flora#146]

**Comment by hschhhwwwo0o** [comment]
https://element.eleme.io/#/en-US/component/notification#with-types

**Comment by hschhhwwwo0o** [comment]
По типу такого

**Comment by hschhhwwwo0o** [comment]
Нужно 2 новые иконки

галочка (успешно бля)
крестик (пиздец бля)

**Comment by hschhhwwwo0o** [comment]
иконки типо чтобы показать успешное ли действие произошло или нет

**Comment by hschhhwwwo0o** [comment]
уведомление через несколько секунд должн озакрываться автоматически (как в примере)

**Comment by StellRay666s** [comment]
ебать, кравислв
