### ISSUE TITLE
Компонент Footer

### ISSUE THREAD

**Issue by hschhhwwwo0o** [StellRay666s/flora#26]
![Image](https://user-images.githubusercontent.com/67684768/176201672-13cd3bca-2496-45c7-b629-6648fca70c78.png)

**Comment by hschhhwwwo0o** [comment]
У нас нету всех этих ссылок, надо подумать как быть с футером

**Comment by StellRay666s** [comment]
Можно просто сделать без ссылок, а на заголовки можно скроллинг повесить
