### ISSUE TITLE
Компонент кнопка

### ISSUE THREAD

**Issue by hschhhwwwo0o** [StellRay666s/flora#29]
![Image](https://user-images.githubusercontent.com/67684768/176197661-5f459d30-f7cb-48ea-bb70-8bde186be91d.png)

![Image](https://user-images.githubusercontent.com/67684768/176204621-16ed7871-dde9-444c-810f-c2280882cd20.png)

**Comment by hschhhwwwo0o** [comment]
2 стиля у кнопок есть

Либо делаешь 2 отдельный компонента, либо меняешь стили через props

**Comment by hschhhwwwo0o** [comment]
Так же можно добавить в кнопке аттрибуты aria-label, title

Роботам будет легче сканировать сайт

**Comment by StellRay666s** [comment]
Сэр есть сэр!

**Comment by hschhhwwwo0o** [comment]
должен быть проп onClick
