### ISSUE TITLE
Функция для валидации емейла

### ISSUE THREAD

**Issue by hschhhwwwo0o** [StellRay666s/flora#60]
Через регулярное выражение, его легко нагуглить

**Comment by hschhhwwwo0o** [comment]
для подобных функций сделай папку utils

utils/validateEmail.js

**Comment by StellRay666s** [comment]
Сэр есть сэр!

**Comment by hschhhwwwo0o** [comment]
Принимает в себя строку емейла, определяет корректен ли емейл, возвращает булиан 

@StellRay666s
